version: '2'
services:
    poc3_jhipster_customize_ui-app:
        image: poc3_jhipster_customize_ui
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://poc3_jhipster_customize_ui-mysql:3306/poc3_jhipster_customize_ui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://poc3_jhipster_customize_ui-elasticsearch:9200
        ports:
            - 8080:8080
    poc3_jhipster_customize_ui-mysql:
        extends:
            file: mysql.yml
            service: poc3_jhipster_customize_ui-mysql
    poc3_jhipster_customize_ui-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: poc3_jhipster_customize_ui-elasticsearch
